# Generated by Django 4.1.7 on 2023-03-12 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(verbose_name='what is it?')),
                ('use_case', models.TextField(blank=True, null=True, verbose_name='why do I need/want and how will I use it?')),
                ('fulfilled', models.BooleanField(default=False)),
                ('date_fulfilled', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoalImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='goals/images/')),
                ('alt', models.CharField(max_length=100)),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal_image', to='goals.goal')),
            ],
        ),
    ]
