# Generated by Django 4.1.7 on 2023-03-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='image',
            field=models.ImageField(default=1, upload_to='goals/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='image_alt',
            field=models.CharField(default='alt', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GoalImage',
        ),
    ]
