# Generated by Django 4.1.7 on 2023-03-18 03:57

from django.db import migrations, models
import goals.models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_image_goal_image_alt_delete_goalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.ImageField(upload_to=goals.models.Goal.get_file_path),
        ),
    ]
