# Generated by Django 4.1.7 on 2023-04-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_created_alter_goal_image'),
        ('goals', '0004_alter_goal_created'),
    ]

    operations = [
    ]
