# Generated by Django 4.1.7 on 2023-05-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_merge_20230411_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
