# Generated by Django 4.1.7 on 2023-05-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goal_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-priority']},
        ),
    ]
