# Generated by Django 4.1.7 on 2023-04-10 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatus',
            fields=[
                ('origin', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('commissions_open', models.BooleanField(default=False)),
                ('requests_open', models.BooleanField(default=False)),
                ('art_trades_open', models.BooleanField(default=False)),
                ('store_open', models.BooleanField(default=False)),
                ('website_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathname', models.CharField(max_length=255)),
                ('view_count', models.IntegerField(default=1)),
                ('site_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='site_status.sitestatus')),
            ],
        ),
    ]
