# Generated by Django 4.1.7 on 2023-04-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
