# Generated by Django 4.1.7 on 2023-05-02 18:14

import commissions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('short_description', models.CharField(max_length=500)),
                ('verbose_description', models.TextField()),
                ('adult', models.BooleanField(default=False)),
                ('abdl', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('ad_blurb', models.TextField()),
                ('should_be_featured', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abdl', models.BooleanField(default=False)),
                ('adult', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('adult', models.BooleanField(default=False)),
                ('abdl', models.BooleanField(default=False)),
                ('exclusive_with', models.CharField(max_length=100)),
                ('required', models.CharField(blank=True, max_length=100, null=True)),
                ('example_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual', models.FileField(max_length=250, upload_to='commissions/visuals/')),
                ('adult', models.BooleanField(default=False)),
                ('abdl', models.BooleanField(default=False)),
                ('is_video', models.BooleanField(default=False)),
                ('group_identifier', models.CharField(default=commissions.models.CommissionVisual.get_uuid, max_length=100)),
                ('order', models.IntegerField()),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_visuals', to='commissions.commission')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('customer_name', models.CharField(max_length=250)),
                ('where_to_contact', models.CharField(choices=[('TG', 'Telegram'), ('DC', 'Discord'), ('TW', 'Twitter'), ('FA', 'FurAffinity')], max_length=2)),
                ('contact_info', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('abdl', models.BooleanField()),
                ('adult', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('artist_note', models.TextField(blank=True, null=True)),
                ('extra_character_details', models.TextField(blank=True, null=True)),
                ('commission_description', models.TextField()),
                ('number_of_characters', models.IntegerField()),
                ('customer_sketch', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='commissions.commission')),
                ('selected_options', models.ManyToManyField(to='commissions.commissionoption')),
                ('statuses', models.ManyToManyField(to='commissions.commissionstatus')),
            ],
        ),
        migrations.AddField(
            model_name='commission',
            name='categories',
            field=models.ManyToManyField(to='commissions.commissioncategory'),
        ),
        migrations.AddField(
            model_name='commission',
            name='options',
            field=models.ManyToManyField(to='commissions.commissionoption'),
        ),
        migrations.CreateModel(
            name='CharacterReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=250)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=commissions.models.CharacterReference.get_file_path)),
                ('adult', models.BooleanField()),
                ('abdl', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_references', to='commissions.commissionorder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='characterreference',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('image__isnull', False), ('link__isnull', False)), models.Q(('image__isnull', True), ('link__isnull', True)), _connector='OR'), name='link_or_image_required'),
        ),
    ]
