# Generated by Django 4.1.7 on 2023-05-08 08:50

import commissions.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionvisual',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='commission',
            name='ad_image',
            field=models.ImageField(blank=True, upload_to=commissions.models.Commission.get_file_path),
        ),
        migrations.AlterField(
            model_name='commission',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commissionoption',
            name='example_image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commissionoption',
            name='exclusive_with',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
