# Generated by Django 4.1.7 on 2023-05-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_commissionvisual_options_commission_ad_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterreference',
            name='text_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
