# Generated by Django 4.1.7 on 2023-05-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_characterreference_text_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='base_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commissionorder',
            name='customer_sketch',
            field=models.TextField(blank=True, null=True),
        ),
    ]
