name: Deploy on push

on:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "placeholder-text"
      - name: Adding Known Hosts
        run: ssh-keyscan -H scuzzyfox.com >> ~/.ssh/known_hosts
      - name: Sync the remote repo and build app
        run: ssh ubuntu@scuzzyfox.com
        run: cd ~/git-repos/scuzzy-site-api
        run: git pull origin main
        run: source env/bin/activate
        run: pip install -r requirements.txt
        run: export DJANGO_SETTINGS_MODULE=siteapi.settings_prod
        run: cd siteapi
        run: python3 manage.py makemigrations
        run: python3 manage.py migrate
        run: python3 manage.py collectstatic -y
        run: python3 -m gunicorn siteapi.asgi:application -k uvicorn.workers.UvicornWorker --daemon
